[theme]
base = "light"
primaryColor = "#0D6468"
backgroundColor = "#F5F7F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182A32"
font = "sans serif"

[server]
headless = true
address = "127.0.0.1"

[browser]
gatherUsageStats = false
